### ISSUE TITLE
gitea isn't being updated

### ISSUE THREAD

**Issue by manics** [conda-forge/gitea-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package hasn't received updates since the only version 1.2 was released in 2017:
https://anaconda.org/conda-forge/gitea/files

The current release of Gitea is 1.21.4:
https://github.com/go-gitea/gitea/releases

There are no automatic bot PRs to update the versions

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by manics** [comment]
It's downloading pre-built binaries:
https://github.com/conda-forge/gitea-feedstock/blob/876dc8203ff7ae4445a6228fa22acd18d6bc70a5/recipe/meta.yaml#L12-L17
so I presume this pre-dates the conda-forge standard of building from source?

It's a Go package and conda-forge support for Go has improved a lot, so maybe it's not too difficult to do this properly....

**Comment by ocefpaf** [comment]
> so I presume this pre-dates the conda-forge standard of building from source?

Very likely

> It's a Go package and conda-forge support for Go has improved a lot, so maybe it's not too difficult to do this properly....

If you can give it a go, please send a PR. I don't know how active the current maintainer is and/or if they are interested in fixing this package.

**Comment by manics** [comment]
I've managed to get a build for MacOS and Linux only: https://github.com/conda-forge/gitea-feedstock/pull/4
